name: duplicate-projects

run-name: Duplicate Projects
on:
  schedule:
    - cron: '41 0/8 * * *'
      # 混雑時間帯を避けた適当な時間
  workflow_dispatch:
jobs:
  duplicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno run --allow-net=scrapbox.io --allow-read=./ --allow-env mod.ts
        env:
          SID: ${{ secrets.SID }}
          SOURCE_PROJECT_NAME: ${{ secrets.SOURCE_PROJECT_NAME }}
          DESTINATION_PROJECT_NAME: ${{ secrets.DESTINATION_PROJECT_NAME }}